### PR TITLE
Avoid `panel_decomposition_mod` causing a divide-by-zero

### LINKED ISSUE #226: Avoid `panel_decomposition_mod` causing a divide-by-zero
### Are there any linked Issues or Pull Requests?

- linked MetOffice/lfric_apps#85

### Brief description

This issue was found in development of the JADA benchmark.

### Further details of the issue.

 Other changes made meant that `jedi_lfric_tests` was crashing due to a divide by zero here:
https://github.com/MetOffice/lfric_core/blob/a4caea11d9984b109fe00d8309a6f135b1cdf59a/infrastructure/source/mesh/panel_decomposition_mod.f90#L252
`mp` is initialised here:
https://github.com/MetOffice/lfric_core/blob/a4caea11d9984b109fe00d8309a6f135b1cdf59a/infrastructure/source/mesh/panel_decomposition_mod.f90#L879-L885
The solution is to instead set `mp = max(1, this_panel_width / shortest_panel_width)`.

### PR DESCRIPTION
**Pull request by tom-j-h**
# PR Summary

Sci/Tech Reviewer: @thomasmelvin 
Code Reviewer: @mike-hobson 

This issue was found in development of the JADA benchmark.

 Other changes made meant that `jedi_lfric_tests` was crashing due to a divide by zero here:
https://github.com/MetOffice/lfric_core/blob/a4caea11d9984b109fe00d8309a6f135b1cdf59a/infrastructure/source/mesh/panel_decomposition_mod.f90#L252
`mp` is initialised here:
https://github.com/MetOffice/lfric_core/blob/a4caea11d9984b109fe00d8309a6f135b1cdf59a/infrastructure/source/mesh/panel_decomposition_mod.f90#L879-L885
The solution is to instead set `mp = max(1, this_panel_width / shortest_panel_width)`.

Please note, I did not find this issue or develop the fix - I just need it for the linked PR below, and there wasn't a PR yet.

- linked MetOffice/lfric_apps#156

- closes #226

## Code Quality Checklist

(_Some checks are automatically carried out via the CI pipeline_)

- [x] I have performed a self-review of my own code
- [x] My code follows the project's
      [style guidelines](https://metoffice.github.io/lfric_core/how_to_contribute/index.html#how-to-contribute-index)
- [x] Comments have been included that aid understanding and enhance the
      readability of the code
- [x] My changes generate no new warnings

## Testing

- [x] I have tested this change locally, using the LFRic Core rose-stem suite
- [x] If required (e.g. API changes) I have also run the LFRic Apps test suite
      using this branch
- [x] If any tests fail (rose-stem or CI) the reason is understood and
      acceptable (e.g. kgo changes)
- [ ] I have added tests to cover new functionality as appropriate (e.g. system
      tests, unit tests, etc.)
- [ ] Any new tests have been assigned an appropriate amount of compute resource
      and have been allocated to an appropriate testing group (i.e. the
      developer tests are for jobs which use a small amount of compute resource
      and complete in a matter of minutes)

### trac.log

I can't find my `trac.log`! It might be because I ran with `--no-run-name`? Here's the Cylc Review: https://cylchub/services/cylc-review/taskjobs/tom.hill/?suite=fix_jelf_divide_by_zero-develop.

## Security Considerations

- [x] I have reviewed my changes for potential security issues
- [ ] Sensitive data is properly handled (if applicable)
- [ ] Authentication and authorisation are properly implemented (if applicable)

## Performance Impact

- [x] Performance of the code has been considered and, if applicable, suitable
      performance measurements have been conducted

## AI Assistance and Attribution

- [ ] Some of the content of this change has been produced with the assistance
      of _Generative AI tool name_ (e.g., Met Office Github Copilot Enterprise,
      Github Copilot Personal, ChatGPT GPT-4, etc) and I have followed the
      [Simulation Systems AI policy](https://metoffice.github.io/simulation-systems/FurtherDetails/ai.html)
      (including attribution labels)

## Documentation

- [ ] Where appropriate I have updated documentation related to this change and
      confirmed that it builds correctly

## PSyclone Approval

- [ ] If you have edited any PSyclone-related code (e.g. PSyKAl-lite, Kernel
      interface, optimisation scripts, LFRic data structure code) then please
      contact the
      [tooscollabdevteam@metoffice.gov.uk](tooscollabdevteam@metoffice.gov.uk)

# Sci/Tech Review

- [ ] I understand this area of code and the changes being added
- [ ] The proposed changes correspond to the pull request description
- [ ] Documentation is sufficient (do documentation papers need updating)
- [ ] Sufficient testing has been completed

_Please alert the code reviewer via a tag when you have approved the SR_

# Code Review

- [ ] All dependencies have been resolved
- [ ] Related Issues have been properly linked and addressed
- [ ] CLA compliance has been confirmed
- [ ] Code quality standards have been met
- [ ] Tests are adequate and have passed
- [ ] Documentation is complete and accurate
- [ ] Security considerations have been addressed
- [ ] Performance impact is acceptable

### CODE REVIEW

File: infrastructure/source/mesh/panel_decomposition_mod.f90 [hunk 1]
```diff
@@ -876,10 +876,10 @@ function calc_mapping_factor( global_mesh_collection, global_mesh ) result(mp)
       end if
     end do
 
-    ! If no meshes were found, return 1. This is relevant for JEDI where mesh
-    ! initialisation is run twice.
+    ! If no meshes were found, or if this_panel_width < shortest_panel_width, then return 1.
+    ! This is relevant for JEDI where mesh initialisation is run twice.
```
Comment (mike-hobson) [inline infrastructure/source/mesh/panel_decomposition_mod.f90]:
```suggestion
```

The second line of this comment is not required. The LFRic infrastructure should be stand-alone. There is no need to mention what application demonstrates a particular issue.
